#!/usr/bin/env php
<?php
while(true) {
    echo '>>> ';
    $line  = fgets(STDIN);
    eval("\$_TOKEN__=$line;");                                                                                                              
    var_dump($_TOKEN__);
}
