#!/bin/bash

if [ $# -eq 0 ];then
echo 'enter one domain'
echo "Usage:$0 test.com"
exit
fi
su <<EOF
arxccv
sleep 1
str=\$(cat /etc/named/other.zone.conf |grep 'zone "'$1'" IN')
echo "\n"
if [ ! -z "\$str" ];then
echo "can not add $1, the zone $1 exists"
exit
fi
echo 'zone "'$1'" IN { type master; file "c.android.clients.google.com.zone";};' >> /etc/named/other.zone.conf
systemctl restart named
EOF
