#!/bin/bash

if [ $# -eq 0 ];then
echo "Error:no specify zone file"
echo "Usage $0 /var/lib/named/check-domain.zone"
exit
fi
randstr=`cat /proc/sys/kernel/random/uuid`
tmp="/tmp/checkzone.tmp.$randstr"

trap 'rm -rf $tmp;wait;exit' INT 
trap 'rm -rf $tmp;wait;exit' TERM

while IFS=' ' read -ra LINE;do
case ${LINE[0]} in
  ns1)
  echo "${LINE[@]}" >> $tmp
continue
  ;;
  ns2)
  echo "${LINE[@]}" >> $tmp
continue
  ;;
  ns3)
  echo "${LINE[@]}" >> $tmp
continue
 ;;
ns4)
  echo "${LINE[@]}" >> $tmp
continue
;;
esac

IP=${LINE[3]}
if [ -z $IP ];then
  echo "${LINE[@]}" >> $tmp
continue
fi
case $IP in
   SOA)
  echo "${LINE[@]}" >> $tmp
  continue
   ;;
  NS)
  echo "${LINE[@]}" >> $tmp
  continue
   ;;
esac
if [ $IP == 'IN' ];then
  echo "${LINE[@]}" >> $tmp
continue;
fi
echo -n "connect $IP"
timeout 5 bash -c "echo >/dev/tcp/$IP/443" >/dev/null 2>&1 && (echo "${LINE[@]}" >> $tmp;echo " Success") ||  echo -e "\033[1;31m Timeout\033[0m"
wait
done < $1
wait
mv $tmp $1
ef=`getenforce`
if [ $ef != 'Disabled' ];then
chcon -t named_zone_t $1
fi
