#!/bin/bash

if [ $# -eq 0 ];then
echo "Error:no specify zone file"
echo "Usage $0 /var/lib/named/check-domain.zone"
exit
fi
randstr=`cat /proc/sys/kernel/random/uuid`
tmp="/tmp/checkzone.tmp.$randstr"

trap 'rm -rf $tmp;wait;exit' INT 
trap 'rm -rf $tmp;wait;exit' TERM

ZONE=`basename $1 .zone`

while IFS=' ' read -ra LINE;do
case ${LINE[0]} in
  ns1)
  echo "${LINE[@]}" >> $tmp
continue
  ;;
  ns2)
  echo "${LINE[@]}" >> $tmp
continue
  ;;
  ns3)
  echo "${LINE[@]}" >> $tmp
continue
 ;;
ns4)
  echo "${LINE[@]}" >> $tmp
continue
;;
esac

IP=${LINE[3]}
if [ -z $IP ];then
  echo "${LINE[@]}" >> $tmp
continue
fi
case $IP in
   SOA)
  echo "${LINE[@]}" >> $tmp
  continue
   ;;
  NS)
  echo "${LINE[@]}" >> $tmp
  continue
   ;;
   CNAME)
  echo "${LINE[@]}" >> $tmp
  continue
  ;;
esac
if [ ${LINE[2]} == 'CNAME' ];then
  echo "${LINE[@]}" >> $tmp
  continue;
fi
if [ $IP == 'IN' ];then
  echo "${LINE[@]}" >> $tmp
    continue;
fi
echo -n "connect $IP"

#timeout 5 bash -c "echo >/dev/tcp/$IP/443" >/dev/null 2>&1 && (echo "${LINE[@]}" >> $tmp;echo " Success") ||  echo -e "\033[1;31m Timeout\033[0m"
NS=${LINE[0]}

if [ "$NS" == '*' ];then
    NS='www'
fi
DS="$NS.$ZONE"

OPENRE=`echo "\r\n" | timeout 5 openssl s_client -host $IP -port 443 -verify_hostname $DS -4 -quiet --verify 1 -prexit -crlf  2>&1`
ORN=$?
if [ $ORN -gt 0 ];then
    echo -e "\033[1;31m Timeout\033[0m"
	continue
fi

echo $OPENRE | grep -q mismatch
GRN=$?
if [ $GRN -gt 0 ];then
    echo "${LINE[@]}" >> $tmp;
    echo " Success"
else
    echo -e "\033[1;31m Mismatch for $DS\033[0m"
fi

wait
done < $1
wait
mv $tmp $1
#rm $tmp
ef=`getenforce`
if [ $ef != 'Disabled' ];then
chcon -t named_zone_t $1
fi
