#!/bin/bash
trap 'EX=1;exit' INT 
trap 'EX=1;exit' TERM
EX=0
CACHE=$(dirname $(realpath $0))/cacheip.txt
echo '' > $CACHE
if [ $# -eq 1 ];then
    ds=$1
    IFS='.' read -ra NSP <<< "$ds"
    if [ ${#NSP[@]} -lt 3 ];then
        A='@'
    else
       SUB=$[${#NSP[@]} - 2]
       A=${NSP[@]:0:$SUB}
    fi
else
    ds='www.gogle.com'
    A='*'
fi
curl -s http://public-dns.info/nameservers.txt | while read -ra LINE;do
    if [ $EX -eq 1 ];then
        exit
    fi
    ns=$LINE
    NS_IPV6=`echo $ns | grep ':'`
    NS_CHK_IPV6=$?
    if [ $NS_CHK_IPV6 -eq 0 ];then
        continue
    fi

    dig $ds @$ns +tcp | while read -ra LINE;do
{
        if [ $EX -eq 1 ];then
            exit
        fi
        cont=0
        F=${LINE[0]:0:1} 
        case $F in
            ';')
            continue
            ;;
        esac

        if [ -z $F ];then
            continue
        fi

        if [ "${LINE[3]}" == 'A' ];then
            IP=${LINE[4]}
            IPV6=`echo $IP | grep ':'`
            CHK_IPV6=$?
            if [ $CHK_IPV6 -eq 0 ];then
               continue
            fi
            grep -q $IP $CACHE
            RET=$?
            if [ $RET -eq 0 ];then
                continue
            fi
            echo $IP >> $CACHE

            #timeout 5 bash -c "echo >/dev/tcp/$IP/443" >/dev/null 2>&1 && echo "$A IN A $IP"
            OPENRE=`echo "\n" | timeout 5 openssl s_client -host $IP -port 443 -verify_hostname $ds -4 -quiet --verify 1 -prexit -crlf  2>&1`
	        ORN=$?
            if [ $ORN -gt 0 ];then
    	    	continue
	        fi
	        echo $OPENRE |grep -q mismatch
	        GRN=$?
	        if [ $GRN -gt 0 ];then
		        echo "$A IN A $IP"
            fi
            wait
        fi
        
}&
    done
    wait
done
