#!/bin/bash
#
# Toknot phpdoc creater ( http://toknot.com )
# @copyright  Copyright (c) 2011 - 2018 Toknot.com
# @license    http://toknot.com/LICENSE.txt New BSD License
# @link       https://github.com/chopins/chopins.github.com
#


#set your default locale language
LAN='zh'
set -x

function usage() {
    echo 'Usage phpdoc co [YOUR_PATH]  create local php doc viewer,创建本地文档项目'
    echo '      phpdoc up [YOUR_PATH]  update local php doc, 更新本地文档'
    echo '      phpdoc [YOUR_PATH]     update local php doc, 默认更新本地文档'
    exit 255 
}

function checkcmd() {
    $1 --version > /dev/null
    if [ $? -gt 0 ];then
        echo "$1 command not found, need install or add environment path"
        exit 127
    fi
}

function looprun() {
   cnt=1
   RET=1
   while [[ $RET -gt 0 && $cnt -lt 5 ]]
   do
	$1
	RET=$?
	cnt=$(($cnt+1))
	wait
   done
}

if [ $# -eq 0 ];then
    usage
fi
if [ $# -eq 1 ];then
    PHP_DOC_WEB=`pwd`
    OP='up'
elif [ $# -ge 2 ];then
    OP=$1
    PHP_DOC_WEB=$(realpath $2)
fi

if [ $OP != 'up' ] && [ $OP != 'co' ];then
    usage
fi

checkcmd rsync
checkcmd svn
checkcmd php
checkcmd phd
checkcmd sed
checkcmd wget
checkcmd which

PHD_PATH=`which phd`
PHD_PATH=`realpath $PHD_PATH`
PHP_CMD='php -d memory_limit=-1' 

if [ ! -e $PHP_DOC_WEB ];then
    mkdir $PHP_DOC_WEB
elif [ ! -d $PHP_DOC_WEB ];then
    echo "Error:File $PHP_DOC_WEB is exists"
    exit
fi

cd $PHP_DOC_WEB

looprun 'rsync -avzC --timeout=60 --delete --delete-after --exclude=manual --exclude=distributions --exclude=extra  --exclude=backend/events --exclude=backend/notes rsync.php.net::phpweb ./webroot'

if [ $OP == 'co' ]; then
    looprun 'svn co http://svn.php.net/repository/phpdoc/doc-base/trunk doc-base'
    looprun 'svn co http://svn.php.net/repository/phpdoc/en/trunk en'
    looprun "svn co http://svn.php.net/repository/phpdoc/$LAN/trunk $LAN"
elif [ $OP == 'up' ];then
    looprun 'svn up doc-base'
    looprun 'svn up en'
    looprun "svn up $LAN"
fi
$PHP_CMD doc-base/configure.php --lang=en
$PHP_CMD $PHD_PATH -d doc-base/.manual.xml -o output/en -f php -P PHP

$PHP_CMD doc-base/configure.php --lang=zh
$PHP_CMD $PHD_PATH -d doc-base/.manual.xml -o output/zh -f php -P PHP

if [ ! -e ./webroot/manual ];then
   mkdir ./webroot/manual
fi

if [ ! -e ./webroot/manual/en ];then
ln -s $PHP_DOC_WEB/output/en/php-web ./webroot/manual/en
fi
if [ ! -e ./webroot/manual/$LAN ];then
ln -s $PHP_DOC_WEB/output/zh/php-web ./webroot/manual/$LAN
fi

echo "Create change.php file"
echo "<?php header(\"Location:{\$_GET['page']}\");" > ./webroot/manual/change.php

sed -i 's/window.location = \(.*\);/window.location = \1 +".php";/g' ./webroot/js/search.js

echo "Replace jquery to local file"
wget http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js -O ./webroot/js/jquery.min.js
sed -i '/ajax\.googleapis\.com/d' ./webroot/include/footer.inc
sed -i 's/\$jsfiles = array(/$jsfiles = array("jquery.min.js",/g' ./webroot/include/footer.inc
echo "Web Root is: $PHP_DOC_WEB/webroot"
echo "==================================================="
echo "Below is nginx rewrite config"
echo 'location / {'
echo '     try_files $uri  $uri/ $uri.php;'
echo '     if ( !-f $request_filename ) {'
echo '          rewrite ^/([a-z0-9\_\-]+) /manual/$cookie_LAST_LANG/function.$1.php;'
echo '     }'
echo '}'

