#!/bin/sh

function gstat() {
    svn status | while read line
    do
    if [ ${line:0:3} == 'svn' ];then
        return 1
    fi
    echo 'FALSE'
    FILE=$(realpath "${line:8}")
    echo "\"$(basename $FILE)\""
    stat="${line:0:1}"
    if [ "$stat" == '?' ];then
        echo 'No'
    elif [ "$stat" == 'M' ];then
        echo "\"Location Modify\""
    elif [ "$stat" == 'D' ];then
	echo "\"Location Delete\""
    fi
    if [ -d "$FILE" ];then
        echo "Dir"
    else
        echo "File"
    fi
    echo "\"$FILE\""
    done
}
LIST=$(gstat | tr -t '\n' ' ')
if [ -z "$LIST" ];then
    exit
fi
function gmsg() {
    MSG=$(zenity --text-info --editable --title="Enter commit message" --text="commit message:" "")
    MST=$?
    if [ $MST -eq 1 ];then
        echo "cancel"
        return 1
    fi
    if [ -z "$MSG" ];then
        zenity --error  --text="必须输入提交评论"
        MSG=$(gmsg)
        if [ $? -eq 1 ];then
            echo "cancel"
            return 1
        fi
    fi
    echo $MSG
}

function commit() {
    MSG=$(gmsg)    
    MST=$?
    if [ $MST -eq  1 ];then
        echo 'cancel'
        return 1
    fi
    LIST=${1// /\\ }
    LIST=${LIST//|/ }
    cmd="svn ci --force-log $LIST -m\"$MSG\""
    echo "Exec:$cmd"
    eval $cmd;echo "100"
}

GET_EVAL="zenity --print-column=5 --title='Commit Change' --width=600 --height=500 --list --text='Select Commit File' --separator='|' --column='Commit' --column='File' --column='Status' --column='File Type' --column='Path' --checklist --multiple $LIST"

FILE_LIST=$(eval $GET_EVAL)
FST=$?

if [ $FST -eq 1 ];then
    echo "cancel"
    exit
fi
echo $FILE_LIST
if [ -z "$FILE_LIST" ];then
    zenity --error  --text="没有选择文件,将退出"
    exit
fi

commit "$FILE_LIST"
