#!/bin/sh

function gstat() {
    svn status | while read line
    do
    echo '0'
    FILE=$(realpath "${line:8}")
    echo "\"$FILE\""
    stat="${line:0:1}"
    if [ "$stat" == '?' ];then
        echo 'No'
    else
        echo "$stat"
    fi
    if [ -d "$FILE" ];then
        echo "Dir"
    else
        echo "File"
    fi
    done
}
LIST=$(gstat | tr -t '\n' ' ')
function gmsg() {
    MSG=$(zenity --entry --title="Enter commit message" --text="commit message:" --entry-text "")
    MST=$?
    echo $MST
    if [ $MST -eq 1 ];then
        echo "cancel"
        return 1
    fi
    if [ -z "$MSG" ];then
        zenity --error  --text="必须输入提交评论"
        MSG=$(gmsg)
        if [ $? -eq 1 ];then
            echo "cancel"
            return 1
        fi
    fi
    echo $MSG
}

function commit() {
    MSG=$(gmsg)    
    MST=$?
    if [ $MST -eq  1 ];then
        echo 'cancel'
        return 1
    fi
    LIST=${1// /\\ }
    LIST=${LIST//|/ }
    cmd="svn ci --force-log $LIST -m\"$MSG\""
    echo "Exec:$cmd"
    eval $cmd
}

GET_EVAL="zenity --width=600 --height=500 --list --text='Commit file' --separator='|' --column='?' --column='File' --column='Status' --column='File Type' --checklist --multiple $LIST"
FILE_LIST=$(eval $GET_EVAL)
FST=$?

if [ $FST -eq 1 ];then
    echo "cancel"
    exit
fi

if [ -z "$FILE_LIST" ];then
    zenity --error  --text="没有选择文件,将退出"
    exit
fi

commit "$FILE_LIST"
